In [1]:
import numpy as np
import pandas as pd

Creating a Dataframe

A Pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). Think of it as a spreadsheet or a SQL table inside Python, where each column represents a Pandas Series object

In [2]:
data={
    'Name':['Murali','Devil','Loki','Spidey'],
    'Age':[21,22,25,28],
    'city':['bbsr','bombai','ohio','asgard'],
    'salary':[20000,25000,15000,16000]
    
}
df=pd.DataFrame(data)

In [31]:
df

     Name  Age    city  salary
0  Murali   21    bbsr   20000
1   Devil   22  bombai   25000
2    Loki   25    ohio   15000
3  Spidey   28  asgard   16000

Selection and indexing of coloumns

In [33]:
df['Name']

0    Murali
1     Devil
2      Loki
3    Spidey
Name: Name, dtype: str

Adding new columns

In [12]:
df['Designation']=['Eng.','Worker','Majdur','Student']
df

     Name  Age    city  salary Designation
0  Murali   21    bbsr   20000        Eng.
1   Devil   22  bombai   25000      Worker
2    Loki   25    ohio   15000      Majdur
3  Spidey   28  asgard   16000     Student

Removing coloumns

In [ ]:
df.drop(["Name",'Age'],axis=1) #axis =0 for horizontal drop and axis =1 is for verticaL drop

     city  salary Designation
0    bbsr   20000        Eng.
1  bombai   25000      Worker
2    ohio   15000      Majdur
3  asgard   16000     Student

In [14]:
df.drop(0,axis=0)

     Name  Age    city  salary Designation
1   Devil   22  bombai   25000      Worker
2    Loki   25    ohio   15000      Majdur
3  Spidey   28  asgard   16000     Student

Selecting Rows

In [ ]:
df.loc[0] #loc is used to locate the rows

Name           Murali
Age                21
city             bbsr
salary          20000
Designation      Eng.
Name: 0, dtype: object

In [26]:
df.loc[[0,1]]

     Name  Age    city  salary Designation
0  Murali   21    bbsr   20000        Eng.
1   Devil   22  bombai   25000      Worker

Selecting Subsets of rows and coloumns

In [24]:
df.loc[[0,1]][['city','salary']]

     city  salary
0    bbsr   20000
1  bombai   25000

In [27]:
df.loc[[2,3]][['Name','Age']]

     Name  Age
2    Loki   25
3  Spidey   28