In [1]:
import numpy as np
import pandas as pd

Merging 2 data frames

In [2]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Natha','Thor','Alice','Lee'],
    'department':['wwe','Cse','mcu','borderland','HR']
})

#dataframe 2
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[100000,50000,12000,6900,54100],
    'bonus':[200,2000,1200,10,690]
    
})

In [3]:
employees

   employee_id   name  department
0            1   John         wwe
1            2  Natha         Cse
2            3   Thor         mcu
3            4  Alice  borderland
4            5    Lee          HR

In [4]:
salaries

   employee_id  salary  bonus
0            1  100000    200
1            2   50000   2000
2            3   12000   1200
3            6    6900     10
4            7   54100    690

In [5]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John        wwe  100000    200
1            2  Natha        Cse   50000   2000
2            3   Thor        mcu   12000   1200

In [8]:
pd.merge(employees,salaries, on='employee_id',how="inner")

   employee_id   name department  salary  bonus
0            1   John        wwe  100000    200
1            2  Natha        Cse   50000   2000
2            3   Thor        mcu   12000   1200

In [10]:
pd.merge(employees,salaries,on='employee_id',how="outer")

   employee_id   name  department    salary   bonus
0            1   John         wwe  100000.0   200.0
1            2  Natha         Cse   50000.0  2000.0
2            3   Thor         mcu   12000.0  1200.0
3            4  Alice  borderland       NaN     NaN
4            5    Lee          HR       NaN     NaN
5            6    NaN         NaN    6900.0    10.0
6            7    NaN         NaN   54100.0   690.0

In [11]:
pd.merge(employees,salaries, on='employee_id',how="left")

   employee_id   name  department    salary   bonus
0            1   John         wwe  100000.0   200.0
1            2  Natha         Cse   50000.0  2000.0
2            3   Thor         mcu   12000.0  1200.0
3            4  Alice  borderland       NaN     NaN
4            5    Lee          HR       NaN     NaN

In [12]:
pd.merge(employees,salaries, on='employee_id',how="right")

   employee_id   name department  salary  bonus
0            1   John        wwe  100000    200
1            2  Natha        Cse   50000   2000
2            3   Thor        mcu   12000   1200
3            6    NaN        NaN    6900     10
4            7    NaN        NaN   54100    690

Concatenation of dataframes

In [14]:
df1=pd.DataFrame({
    'A':['A0','B0','C0'],
    'B':['A1','B1','C1'],
    'C':['A2','B2','C2']
})
df2=pd.DataFrame({
    'A':['A3','B3','C3'],
    'B':['A4','B4','C4'],
    'C':['A5','B5','C5']
})

In [15]:
df1

    A   B   C
0  A0  A1  A2
1  B0  B1  B2
2  C0  C1  C2

In [16]:
df2

    A   B   C
0  A3  A4  A5
1  B3  B4  B5
2  C3  C4  C5

In [18]:
pd.concat([df1,df2])

    A   B   C
0  A0  A1  A2
1  B0  B1  B2
2  C0  C1  C2
0  A3  A4  A5
1  B3  B4  B5
2  C3  C4  C5

In [ ]:
pd.concat([df1,df2],axis=1)#for row concatenation

    A   B   C   A   B   C
0  A0  A1  A2  A3  A4  A5
1  B0  B1  B2  B3  B4  B5
2  C0  C1  C2  C3  C4  C5